seefoodSAAS/recognition/urls.py
from django.urls import path

from . import views

app_name = 'recognition'
urlpatterns = [
    path('', views.home),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('process/', views.process, name='process'),
    path('results/', views.results, name='results'),
]

seefoodSAAS/seefoodSAAS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seefood/', include('recognition.urls')),
]

seefoodSAAS/recognition/models.py
from django.db import models

# Create your models here.

seefoodSAAS/recognition/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    # Ideally you should use ImageField but for that you will
    # have to install plugins for pillow to support different formats
    image_file = forms.FileField(label='Upload image')

seefoodSAAS/recognition/views.py
import json
import os
import shutil
import socket

import subprocess
from pathlib import Path

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from recognition.forms import ImageUploadForm

context = {}


def home(request):
    return HttpResponse("SeeFood Homepage!")


# TODO: Try using ResultsView commented below instead
def results(request):
    context['hostname'] = socket.gethostname()
    return render(request, 'recognition/results.html', context)


# Gives error : django.core.exceptions.ImproperlyConfigured: ResultsView is missing a QuerySet.
# Define ResultsView.model, ResultsView.queryset, or override ResultsView.get_queryset().
#
# class ResultsView(generic.ListView):
#     template_name = 'recognition/results.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['json_arr '] = json_arr
#         context['filename'] = filename


class UploadView(generic.FormView):
    template_name = 'recognition/details.html'
    form_class = ImageUploadForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        print("form_invlaid() called!")
        return self.form_valid(form)

    def form_invalid(self, form):
        print("form_invlaid() called!")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        upload_context = super().get_context_data(**kwargs)
        upload_context['container_id'] = socket.gethostname()
        return upload_context


def process(request):
    uploaded_file = request.FILES['image_file']

    location = 'media/' + str(uploaded_file.name).split('.')[0]
    print("location: ", location)
    if Path(location).exists():
        shutil.rmtree(location)

    fs = FileSystemStorage(location=location)
    filename = fs.save(uploaded_file.name, uploaded_file)
    uploaded_file_url = fs.url(filename)
    print("Image saved at: ", uploaded_file_url)

    print("Processing image...")
    current_path = os.getcwd()
    output = subprocess.run(['flow', '--pbLoad', '../darkflow/built_graph/Adam/tiny-yolo-coco-4c.pb',
                             '--metaLoad', '../darkflow/built_graph/Adam/tiny-yolo-coco-4c.meta',
                             '--imgdir', location, '--json'])

    if output.returncode == 0:
        json_path = os.path.join(current_path, location, 'out')
        json_filename = str(filename).split('.')[0] + '.json'
        json_arr = json.load(open(os.path.join(json_path, json_filename)))
    else:
        return render(request, 'recognition/details.html', {'error_message': 'Error processing the image...'})

    global context
    context = {'json_arr': json_arr, 'filename': filename}
    return HttpResponseRedirect(reverse('recognition:results'))

seefoodSAAS/recognition/templates/recognition/details.html
<head>
    <title>Upload | SeeFood</title>
    <style>
        html, body {
            height: 100%;
        }

        html {
            display: table;
            margin: auto;
        }

        body {
            display: table-cell;
            vertical-align: middle;
        }
    </style>
</head>


{% if container_id %}
    <p><strong>Served by container ID {{ container_id }}</strong></p>
{% endif %}

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form enctype="multipart/form-data" action="{% url 'recognition:process' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br><br>
    <input type="submit" value="Submit" />
</form>

seefoodSAAS/recognition/templates/recognition/results.html
<head>
    <title>Results | SeeFood</title>
    <style>
        html, body {
            height: 100%;
        }

        html {
            display: table;
            margin: auto;
        }

        body {
            display: table-cell;
            vertical-align: middle;
        }
    </style>
</head>

<h3>Detected objecs in {{ filename }}</h3>

<p><strong>Served by Container ID {{ hostname }}</strong></p>

<ol>
    {% for arr in json_arr %}
        <li>{{ arr }}</li>
    {% endfor %}
</ol>

<a href="{% url 'recognition:upload' %}">Try another image?</a>